development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://vyrxexfbtoxltm:hRJLGOy6_TfY4l0hSzdf_nXu6Y@ec2-54-235-89-113.compute-1.amazonaws.com:5432/d9lr2ej53esmda
